### ISSUE TITLE
Subsonic when using custom url doesn't work

### ISSUE THREAD

**Issue by ryanmurray** [borismus/keysocket#246]
I have my subsonic as website/subsonic using nginx proxy to make url simple. Im running subsonic docker. When i access my site the media keys don't work

**Comment by feedbee** [comment]
It doesn't work because of your custom URL. This functionality is currently broken as developers have changed internal URLs so, that they can't be caught by any pattern.

To make it work we have to add custom URL patterns feature, which is planned for future and everybody is welcome to implement it.
