### ISSUE TITLE
Start as off by default / register a hotkey to turn on/off for tab

### ISSUE THREAD

**Issue by martixy** [borismus/keysocket#265]
Default off means managing multiple tabs can become so much easier, as right now you have to go through each opened tab to turn off so only one tab will respond.
Also, a hotkey for that function would be terribly useful.

Alternatively, make it respond to only the latest focused tab, if possible.

**Comment by thepag** [comment]
If you use the `MediaControlStateChanged` event to communicate to the extension, then you may turn the extension on and off as desired. See https://github.com/borismus/keysocket/blob/master/extension/media-control-api.js#L23-L33 for the event code in the extension.

**Comment by ignatremizov** [comment]
I would like to bump this issue, as I would also like to have a "default off" option. It's very annoying when you, say, open 20+ YouTube tabs by going through your notification list, and then having them all accidently play at once because your bluetooth headphones decided to send a play signal request (like say a noise played on your phone, which your bluetooth headphones are also connected to). Thanks.

**Comment by ignatremizov** [comment]
:(

**Comment by martixy** [comment]
> :(

Yea, was cleaning up old issues I've opened. If it's not been done by now, it will never get done. Try to find a different solution?
