### ISSUE TITLE
Spotify Windows 10 app conflict

### ISSUE THREAD

**Issue by ArielMatC** [borismus/keysocket#288]
When keysocket extension is enabled, my keyboard media keys don't work on Spotify Windows app. If I disable keysocket, the media keys work again on Spotify app.
I have Windows 10

**Comment by valery-leontyev-idt** [comment]
Key bindings work with one application at a time. They both can't use them in the same time.

**Comment by neico** [comment]
This also applies to pretty much any application allowing global hotkeys with media keys, for example media players such as VLC.
What is bothersome is that it even happens when there's no tab open that this extension can control. (At least I'm pretty sure there isn't, I do have quite a few windows and tabs open currently)

**Comment by feedbee** [comment]
Global key bindings work with one application at a time. They both can't use them in the same time.
Shortcuts are set via chrome, extension does not control weather binding is active or inactive.
