### ISSUE TITLE
Google Music Simulate Click not Working

### ISSUE THREAD

**Issue by jack-t** [borismus/keysocket#37]
I've installed the python app, and the extension, but the best I can get for a pause is a slight stutter. I think the issue is the `simulateClick` function, and when I run it in the dev tools' console, it doesn't work. I've worked out a solution that works on my solution (it involves the `click()` event on the element retrieved from `document.querySelector()`. I'm not quite sure how to edit the extension to actually run it, so I'm working on that.

**Comment by darrenboyd** [comment]
This might be related, especially to what @EnigmaCurry wrote above...

> I think it's sending the event multiple times. When I click the next button it skips two tracks, for instance.

Note that in Chrome, in Google Play Music, the keys already work *without* this plugin.  Whenever I load Google Play Music, I always have to disable this plugin so the keys work properly (instead of occurring twice, each time I tap them).

(NOTE: I came here wondering if there was a way to auto-disable the plugin on certain sites, and found this issue.)

**Comment by borismus** [comment]
Yep the Play Music extension also provides media keys. If multiple
extensions bind to the media keys, it's a race condition and only one of
them wins. You can configure which one via chrome:extensions.

**Comment by sanscore** [comment]
I'm experiencing the same/similar issue with OSX. When I hit my pause button, it appears that the play/pause button is hit twice. If music is paused, then the button goes to play and back to pause. Same story for when music is playing. The back and forward buttons work flawlessly (they properly advance one track; not two).
