### ISSUE TITLE
Synology standalone app window not supported

### ISSUE THREAD

**Issue by madutis** [borismus/keysocket#85]
Works perfectly when full Synology UI is opened (/webman/index.cgi), however if you open just the AudioStation app separately (/audio/index.cgi), the playback isn't controlled.

**Comment by feedbee** [comment]
That's why ([manifest.json](https://github.com/borismus/keysocket/blob/master/extension/manifest.json#L122)):

```
    {
      "matches": ["*://*/webman/*"],
      "js": ["shared.js","keysocket-dsaudio5.js"]
    },
```

If you want to fix it, you can do it yourself. Fork the code. Download it, change this block to:

```
    {
      "matches": ["*://*/webman/*", "*://*/audio/*"],
      "js": ["shared.js","keysocket-dsaudio5.js"]
    },
```

Then load extension locally and check if it works now. It it is, contribute it (commit changes and open Pull Request).
