### ISSUE TITLE
Lacks support for remote play/pause button on headphones

### ISSUE THREAD

**Issue by fredrikalm** [borismus/keysocket#92]
I can stop/start music on my Synology Audio Station with play/pause key on my mac keyboard, before installing the plugin it just opened iTunes on my computer when pressing the play/pause key, all good. However, it doesn't seem to bind to the play/pause button on my headphones, pressing it still starts iTunes instead of starting/stopping the music.

**Comment by gortloveslinux** [comment]
This has to do with how Mac OSX handles media key events from bluetooth devices. The OS intercepts the event and open Itunes if it isn't already started otherwise toggles Play and pause states. Keysocket never even has a chance since the event isn't sent to the browser. Search the intertubes for rcd (Remote Control Daemon) for discussions of others having this problem.

**Comment by fredrikalm** [comment]
Thanks for making that clear!
